group: Upload wheels to TestPyPI
sort_key: "2"
steps:
  - block: "Upload wheels from S3 to TestPyPI"
    key: block-upload-wheels-testpypi
    depends_on: 
      - forge

  - label: "Upload wheels from S3 to TestPyPI"
    key: upload-wheels-testpypi
    job_env: forge
    instance_type: small_branch
    commands:
      - bazel run //ci/ray_ci/automation:upload_wheels_pypi -- 
        --ray_version="$RAY_VERSION"
        --commit_hash="$BUILDKITE_COMMIT"
        --pypi_env=test

