group: Upload & Validate wheels
steps:
  - label: "Upload wheels to PyPI"
    key: upload-wheels-pypi
    job_env: forge
    instance_type: small_branch
    commands:
      - bazel run //ci/ray_ci/automation:upload_wheels_pypi -- 
        --ray_version="$RAY_VERSION"
        --commit_hash="5708e75978413e46c703e44f43fd89769f3c148b" 
        --pypi_env=prod
